line-length = 150
indent-width = 4
show-fixes = true
exclude = [
    ".venv",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "typings"
]

# Minimum Python version: 3.13
target-version = "py313"

[format]

# Like Black:
# use double quotes for strings.
quote-style = "double"

# indent with spaces, rather than tabs.
indent-style = "space"

# respect magic trailing commas.
skip-magic-trailing-comma = false

# automatically detect the appropriate line ending.
line-ending = "auto"


[lint]
select = [
    "C4",  # flake8-comprehensions
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "ICN", # flake8-import-conventions
    "ISC", # flake8-implicit-str-concat
    "N",   # pep8-naming
    "PL",  # PylLint
    "SIM", # flake8-simplify
    "TCH",  # flake8-type-checking
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade PEP604
    "W",   # warning
]

# Additional rules
# "This is particularly useful in mono repositories
#  where you want to establish a base standard for the entire company
#  but allow projects to customize the configuration to best fit their needs."
extend-select = [
]

fixable = ["ALL"]
ignore = [
    "D1",  # Missing docstring
    "TD",  # TODO
]
